### ISSUE TITLE
asynchronous or multithreaded support?

### ISSUE THREAD

**Issue by vimalloc** [tmoravec/fastjsonrpc#12]
I built an rpc daemon based on the ssl_server.tac in the examples section. It works, but it doesn't seem to be able to work in parallel. I have one rpc call that can take 15 to 30 seconds to complete, and while that is running no other rpc calls are able to be processed by the daemon. I'm assuming there is something in twisted that could be changed to fix this, but I'm having trouble finding anything (first time using twisted).

Any advice?

**Comment by tmoravec** [comment]
Twisted is a framework for building asynchronous applications. In general, you don't use multithreading in this model, although you _can_ use threads if you need  a library that doesn't work asynchronously. Here is a nice article that explains how it works, btw the whole series is a great introduction into Twisted:
http://krondo.com/?p=1209

I suggest you read through all of the series, because writing asynchronous applications is very different to what we are used to.

Let me know if you have more specific questions, or some code that doesn't behave as expected.

**Comment by vimalloc** [comment]
The end goal is to be able to have the fastjsonrpc daemon using ssl and be able to process multiple rpc calls simultaneously. Thanks for posting that link, I'll read it over and see if I can get something going from there.

Cheers.
